import { tags } from "typia";

/**
 * Member interface definition
 * @title Inputtttt
 */
export interface Input {
	/**
	 * Unique user ID generated by server.
	 * @format uuid
	 * @default 123
	 */
	id?: string;

	/**
	 * Type what you'd normally search for in the Google Maps search bar, like <b>English breakfast</b> or <b>pet shelter</b>. Aim for unique terms for faster processing. Using similar terms (e.g., <b>bar</b> vs. <b>restaurant</b> vs. <b>cafe</b>) may slightly increase your capture rate but is less efficient.<br><br> ⚠️ Heads up: Adding a location directly to the search, e.g., <b>restaurant Pittsburgh</b>, can limit you to a maximum of 120 results per search term due to <a href='https://blog.apify.com/google-places-api-limits/#%E2%9B%94-what-are-google-maps-limitations-for-scraping'>Google Maps' scrolling limit</a>.<br><br> You can also use direct place IDs here in the format <code>place_id:ChIJ8_JBApXMDUcRDzXcYUPTGUY</code>.See the [detailed description](https://apify.com/compass/crawler-google-places#search-terms).
	 * @title 🔍 Search term(s)
	 * @editor stringList
	 * @prefill [ "restaurant" ]
	 * @default [ "restaurant" ]
	 */
	searchStringsArray: string[];

	/**
	 * Email address of the member.
	 */
	email: string & tags.Format<"email">;

	/**
	 * Age of the member.
	 *
	 * For reference, only adult can be a member.
	 */
	age: number & tags.Type<"uint32"> & tags.Minimum<19> & tags.Maximum<100>;

	/**
	 * A sample value field.
	 * ignrore
	 * @title true
	 * @editor default
	 */
	value?: number & tags.Default<10>;
}
