/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of URLs to be crawled. They can be search URLs, place URLs or review detail URLs. Valid Google Maps place URLs must contain one of the following subpaths: <code>/maps/search</code>, <code>/maps/place</code> or <code>/maps/reviews</code>.
 */
export type GoogleMapsPlaceURLs = unknown[];
/**
 * List of place IDs. You can add place IDs one by one or upload a list using the <strong>Bulk edit</strong> option.
 */
export type PlaceIDs = unknown[];
/**
 * Max number of reviews per place to scrape. If you fill in 0 or nothing, no reviews will be scraped. For all reviews, just put 99999.
 */
export type NumberOfReviews = number;
/**
 * Define how reviews should be sorted.
 */
export type SortReviewsBy = "newest" | "mostRelevant" | "highestRanking" | "lowestRanking";
/**
 * Either absolute date (e.g. `2024-05-03`) or relative date from now into the past (e.g. `8 days`, `3 months`). JSON input also supports adding time in both absolute (ISO standard, e.g. `2024-05-03T20:00:00`) and relative  (e.g. `3 hours`) formats. Absolute time is always interpreted in the UTC timezone, not your local timezone - please convert accordingly. Supported relative date & time units: `minutes`, `hours`, `days`, `weeks`, `months`, `years`.
 */
export type OnlyScrapeReviewsNewerThanDate = string;
/**
 * Results details will show in this language.
 */
export type Language =
  | "en"
  | "af"
  | "az"
  | "id"
  | "ms"
  | "bs"
  | "ca"
  | "cs"
  | "da"
  | "de"
  | "et"
  | "es"
  | "es-419"
  | "eu"
  | "fil"
  | "fr"
  | "gl"
  | "hr"
  | "zu"
  | "is"
  | "it"
  | "sw"
  | "lv"
  | "lt"
  | "hu"
  | "nl"
  | "no"
  | "uz"
  | "pl"
  | "pt-BR"
  | "pt-PT"
  | "ro"
  | "sq"
  | "sk"
  | "sl"
  | "fi"
  | "sv"
  | "vi"
  | "tr"
  | "el"
  | "bg"
  | "ky"
  | "kk"
  | "mk"
  | "mn"
  | "ru"
  | "sr"
  | "uk"
  | "ka"
  | "hy"
  | "iw"
  | "ur"
  | "ar"
  | "fa"
  | "am"
  | "ne"
  | "hi"
  | "mr"
  | "bn"
  | "pa"
  | "gu"
  | "ta"
  | "te"
  | "kn"
  | "ml"
  | "si"
  | "th"
  | "lo"
  | "my"
  | "km"
  | "ko"
  | "ja"
  | "zh-CN"
  | "zh-TW";
/**
 * Select whether you want all reviews (from Google, Tripadvisor, etc.) or only reviews from Google
 */
export type ReviewsOrigin = "all" | "google";
/**
 * This settings allows you to obtain personal data about reviewer (his ID, name, URL and his photo URL) and about review (ID and URL). Personal data is protected by the GDPR in the European Union and by other regulations around the world. You should not scrape personal data unless you have a legitimate reason to do so. If you're unsure whether your reason is legitimate, consult your lawyers.
 */
export type PersonalData = boolean;

/**
 * Provide either Google place URLs. You will get all the reviews that are connected with the selected Google Place.
 */
export interface GoogleMapsReviewsScraperInput {
  startUrls?: GoogleMapsPlaceURLs;
  placeIds?: PlaceIDs;
  maxReviews?: NumberOfReviews;
  reviewsSort?: SortReviewsBy;
  reviewsStartDate?: OnlyScrapeReviewsNewerThanDate;
  language?: Language;
  reviewsOrigin?: ReviewsOrigin;
  personalData?: PersonalData;
  [k: string]: unknown;
}


import { Actor, type CallOptions } from 'apify';

/**
 * Calls the actor "googleMapsReviewsScraper" with the provided input.
 * @param input - Must conform to the GoogleMapsReviewsScraperInput type.
 * @param runOptions - Optional run options to pass to the actor.
 */
export async function callGoogleMapsReviewsScraper(input: GoogleMapsReviewsScraperInput, runOptions?: CallOptions): Promise<unknown> {
    return Actor.call('Xb8osYTtOjlsgI6k9', input, runOptions);
}
